Check API response for error before 429 check
Simple code ordering switch. The Slack API HTTP response
was previously checked for a 429 - Too Many Requests status, before
checking if the request itself errored. This caused a crash when the
response was not set.

```
TypeError: Cannot read property 'status' of undefined
    at SlackData.onres (/srv/www/node_modules/slackin-extended/dist/slack.js:105:15)
    at /srv/www/node_modules/slackin-extended/dist/slack.js:83:16
```